### PR TITLE
Flowchart parallel

### PR DESCRIPTION
**Pull request by sudhakar-sekar**
Added parallel type for creating multiple path from source to targets.

### CODE REVIEW

**Comment by adrai** [comment]
Can you change the indentations to 2 spaces instead of 4 spaces?

**Comment by sudhakar-sekar** [comment]
No, auto formatting changed that. no any indentations.

**Comment by adrai** [comment]
...still seeing unwanted indentations: https://github.com/adrai/flowchart.js/pull/145/files

**Comment by adrai** [comment]
v1.11.0

**Pull request merged**
