### PR TITLE
type: add types

### PR DESCRIPTION
**Pull request by Mister-Hope**

### CODE REVIEW

**Comment by adrai** [comment]
Is there some possibility to add some dedicated typescript tests?

**Comment by Mister-Hope** [comment]
Nope, I have tested on serveral options and usage.

Unless we move the whole project to typescript, adding test has no meanings.

JS do not have types, so I am just writing type test to test my declaration files structure is the structure I wrote.

**Comment by Mister-Hope** [comment]
I am trying to mirigate to typescript yesterday, but the is a lot of work because the project abuse usage of this, hanging a lot of property. While typescript is requiring all the proerties be declared and typed, so I have to rewrite the whole project.

I am doing the work at https://github.com/Mister-Hope/flowchart.js/tree/ts

**Comment by adrai** [comment]
Thank you very much for your contribution.
Included in v1.15.0

**Pull request merged**
