### PR TITLE
Changes towards modularity

### PR DESCRIPTION
**Pull request by sergeyt**
* changes in favor of explicit dependencies (issue #70)
* webpack-friendly
* code now meets eslint default rules

### CODE REVIEW

**Comment by sergeyt** [comment]
@adrai this PR is ready to merge, please review. Also is it ok to drop release/flowchart.zip file from repository? Usually nobody need to explicitly use zip file and also anyone could download zip or tar file right from github, so I suggest to remove this file.

**Comment by sergeyt** [comment]
Also now build script generates UMD library. So `*.amd.*` files were also removed.

**Comment by adrai** [comment]
Can you add a simple how to "build" section in the readme?

**Comment by adrai** [comment]
nice, i hope i can merge this tomorrow

**Comment by sergeyt** [comment]
FYI `npm run build` is build instruction, please update README.md with better words :)

**Comment by adrai** [comment]
I did not try it, but is it still possible to include the lib the "old-way"?

```
something like this:
<script src="../release/flowchart.js"></script>
```

**Comment by sergeyt** [comment]
> but is it still possible to include the lib the "old-way"

yes, in browser it is exposed as global variable `FlowChart`.

**Pull request merged**
