### PR TITLE
Add arrow-text attribute to symbols

### PR DESCRIPTION
**Pull request by josephtocci**
For my flowchart I had to make a change and label a specific arrow on a operation block. These are my changes.

### CODE REVIEW

**Comment by adrai** [comment]
I'm merging right now... but can you add here a comment on this PR for documentation? So others can see your example?

**Comment by adrai** [comment]
v1.9.0

**Comment by josephtocci** [comment]
There is a particular step in my process where there is only one path, but sometimes that path is temporarily closed and it is best represented with a note on the arrow instead of a decision block.

Not my actual example, but this is how I put the text on the arrow:
```
'flowstate' : {
    'example' : {'arrow-text' : 'Need to wait for other process to finish before proceeding' }
}
```

**Comment by FavorMylikes** [comment]
Can I use it on parallel at different path?

**Pull request merged**
