### PR TITLE
fix: Provide low cost means of lines not colliding until they converge

### PR DESCRIPTION
**Pull request by robertleeplummerjr**
Before:
Screen Shot 2019-11-27 at 3 59 31 PM

After:
Screen Shot 2019-11-27 at 4 01 03 PM

### CODE REVIEW

**Comment by adrai** [comment]
You are awesome!
I will merge, but can you first look at why the example flowchart is now rendering strange? 
image
npm start and open http://localhost:8000/

btw: can you add here some screenshots of some typical example, how they change?

**Comment by robertleeplummerjr** [comment]
Yup, resolving.

**Comment by adrai** [comment]
hehe... no rush... 😉
already late here... will be back tomorrow

**Comment by robertleeplummerjr** [comment]
fixed

**Comment by robertleeplummerjr** [comment]
Before:
image

After:
image

Before:
image

After:
image

Before:
image

After:
image

**Comment by robertleeplummerjr** [comment]
For my purposes, this is what I saw.

Before:
image

After:
image

**Comment by robertleeplummerjr** [comment]
The main fix was for connections between "Thing 3" and  "Thing 4", I found that the layout engine was resilient enough to know how to layout the "Things" (pun intended) if I severed this connection, but when there were doubled + connections beside each other, it caused the weird overlapping issue. of the green and black.  But by adding a feature that was smart enough to count the connections and offset for them, it'd fix this.

FYI.

**Comment by adrai** [comment]
You're great!
This is now included in v1.13.0

**Pull request merged**
